//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSystem_2_.Models.VT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Menu
    {
        public int ID { get; set; }
        public string YemekAd { get; set; }
        public int KategoriID { get; set; }
        public string ResimURL { get; set; }
        public int Fiyat { get; set; }
        public string Acıklama { get; set; }
    
        public virtual Tbl_MenuKategori Tbl_MenuKategori { get; set; }
    }
}
