//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSystem_2_.Models.VT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MenuKategori
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_MenuKategori()
        {
            this.Tbl_Menu = new HashSet<Tbl_Menu>();
        }
    
        public int ID { get; set; }
        public string KategoriAd { get; set; }
        public Nullable<int> UstKategoriID { get; set; }
        public string ResimURL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Menu> Tbl_Menu { get; set; }
    }
}
