//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSystem_2_.Models.VT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FirmaBilgileri
    {
        public int ID { get; set; }
        public string Adres { get; set; }
        public string InstagramURL { get; set; }
        public string FacebookURL { get; set; }
        public string TwitterURL { get; set; }
        public string TelNo { get; set; }
        public string Logo { get; set; }
        public string Eposta { get; set; }
        public string ResimURL { get; set; }
    }
}
